from pathlib import Path

p = Path("docs/V0_1_USAGE.md")
p.parent.mkdir(exist_ok=True)

lines = [
    "# Mercury Goal Runner Harness v0.1 Usage (Windows)",
    "",
    "## What the harness is",
    "",
    "The Mercury Goal Runner Harness is a lightweight framework for running goal-based agent work safely.",
    "",
    "It uses goal contracts: JSON files that describe what the user wants, what final output should exist, what constraints must be followed, what counts as DONE, what counts as failure, and what evidence is required.",
    "",
    "The harness is designed for Mercury V2, but Mercury is not the final authority. Mercury can compile, plan, execute approved steps, and report evidence. The certifier decides whether the run passes.",
    "",
    "## How to validate goal_contract.json",
    "",
    "Use the local schema validator:",
    "",
    "```cmd",
    "python .agentic-pi\\validators\\validate_schema.py .agentic-pi\\schemas\\goal_contract.schema.json .agentic-runs\\real_goal_001\\goal_contract.json",
    "```",
    "",
    "Expected output:",
    "",
    "```text",
    "SCHEMA_VALID",
    "```",
    "",
    "If the validator reports SCHEMA_INVALID, fix the goal contract before running any Worker step.",
    "",
    "## How to run the smoke test",
    "",
    "The deterministic v0.1 smoke test is:",
    "",
    "```cmd",
    "python smoke_v01.py",
    "```",
    "",
    "Expected output:",
    "",
    "```text",
    "DONE_PASS",
    "```",
    "",
    "The smoke test creates a sample run, writes a README artifact, creates a step log, writes a trace event, and calls the certifier.",
    "",
    "## How certification works",
    "",
    "Certification is handled by:",
    "",
    "```cmd",
    "python .agentic-pi\\validators\\certify_run.py .agentic-runs\\real_goal_001",
    "```",
    "",
    "The certifier checks:",
    "",
    "- goal_contract.json exists",
    "- goal_contract.json parses as JSON",
    "- trace.jsonl exists",
    "- trace.jsonl lines parse as JSON",
    "- step_logs contains at least one step result",
    "- step logs contain evidence",
    "- done_criteria is not empty",
    "- final_outputs is not empty",
    "- required final outputs exist",
    "- Worker did not report touching protected files",
    "",
    "The certifier writes:",
    "",
    "- .agentic-runs\\real_goal_001\\certification.json",
    "- .agentic-runs\\real_goal_001\\final_status.md",
    "",
    "These files should be written only by certifier logic, not by Mercury.",
    "",
    "## Why Mercury cannot mark DONE by itself",
    "",
    "Mercury V2 is fast and useful, but it can still overclaim or produce incomplete evidence.",
    "",
    "Mercury is allowed to compile goals, propose plans, create approved artifacts, and report evidence.",
    "",
    "Mercury is not allowed to write final_status.md, write certification.json, declare final DONE_PASS, or certify its own output.",
    "",
    "Core rule:",
    "",
    "```text",
    "Evidence beats confidence.",
    "```",
    "",
    "## Status codes explained",
    "",
    "| Code | Meaning |",
    "|---|---|",
    "| DONE_PASS | All required checks passed and final outputs exist. |",
    "| DONE_FAIL | The run was certified, but one or more required checks failed. |",
    "| BLOCKED | The harness cannot continue because a required dependency, permission, artifact, or decision is missing. |",
    "| NEED_USER | Human input is needed before the run can safely continue. |",
    "| MAX_STEPS_REACHED | The run stopped because it reached the step budget. |",
    "",
    "## Current v0.1 rule",
    "",
    "A run is not successful just because a file was created.",
    "",
    "A run is successful only when:",
    "",
    "1. the Goal Contract is valid,",
    "2. the Worker step log contains evidence,",
    "3. required final outputs exist,",
    "4. trace exists,",
    "5. the certifier writes DONE_PASS.",
    "",
]

p.write_text("\n".join(lines), encoding="utf-8")
print("Wrote ASCII-only docs/V0_1_USAGE.md")