#!/usr/bin/env python3
import argparse
import json
import os
from pathlib import Path


def load_contract(run_dir):
    contract_path = Path(run_dir) / "goal_contract.json"
    if not contract_path.is_file():
        raise FileNotFoundError(f"Goal contract not found at {contract_path}")
    with open(contract_path, encoding='utf-8-sig') as f:
        return json.load(f)


def write_plan(run_dir, planner_name, plan_data):
    plans_dir = Path(run_dir) / "plans"
    plans_dir.mkdir(parents=True, exist_ok=True)
    plan_path = plans_dir / f"{planner_name}_plan.json"
    with open(plan_path, "w") as f:
        json.dump(plan_data, f, indent=2)
    print(f"Wrote {planner_name} plan to {plan_path}")


def main():
    parser = argparse.ArgumentParser(description="Route goal contract to appropriate planners")
    parser.add_argument("--run-id", required=True, help="Run identifier")
    args = parser.parse_args()
    run_dir = Path(".agentic-runs") / args.run_id
    contract = load_contract(run_dir)
    # Determine complexity – default to SIMPLE if not specified
    complexity = contract.get("complexity_level", "SIMPLE").upper()
    print(f"Complexity detected: {complexity}")
    # Generate plans based on complexity
    if complexity == "SIMPLE":
        planners = ["planner-minimal"]
        step = {
            "action": "create_file",
            "path": "README.md",
            "content": "# Simple Goal\n\nGenerated by Mercury."
        }
    elif complexity == "MEDIUM":
        planners = ["planner-minimal", "planner-robust", "planner-skeptic"]
        step = {
            "action": "create_file",
            "path": "docs/examples.md",
            "content": "# Examples\n\n- Example 1\n- Example 2\n- Example 3\n"
        }
    elif complexity == "HARD":
        planners = ["planner-minimal", "planner-robust", "planner-skeptic", "planner-fast", "planner-quality"]
        step = {
            "action": "create_file",
            "path": "cli_tool.py",
            "content": "#!/usr/bin/env python3\n\n# Placeholder CLI tool that processes a CSV and prints a summary\nimport csv, sys\n\ndef main():\n    print('CLI tool placeholder – no real processing')\n\nif __name__ == '__main__':\n    main()\n"
        }
    else:
        # IMPOSSIBLE or unknown – generate a step that will likely fail
        planners = ["planner-minimal"]
        step = {
            "action": "create_file",
            "path": "impossible.txt",
            "content": "This is an impossible goal placeholder."
        }
    # Write a plan for each planner
    for planner_name in planners:
        plan = {"planner": planner_name, "steps": [step]}
        write_plan(run_dir, planner_name, plan)
    # In a full implementation, a selector and merger would run next.

if __name__ == "__main__":
    main()
