#!/usr/bin/env python3
# Deterministic stub planner for testing; not a real adaptive planner.
import argparse
import json
import os
from pathlib import Path


def first_final_output(contract, default_path):
    outputs = contract.get("final_outputs") or []
    if outputs:
        return outputs[0]
    return default_path


def load_contract(run_dir):
    contract_path = Path(run_dir) / "goal_contract.json"
    if not contract_path.is_file():
        raise FileNotFoundError(f"Goal contract not found at {contract_path}")
    with open(contract_path, encoding='utf-8-sig') as f:
        return json.load(f)


def write_plan(run_dir, planner_name, plan_data):
    plans_dir = Path(run_dir) / "plans"
    plans_dir.mkdir(parents=True, exist_ok=True)
    plan_path = plans_dir / f"{planner_name}_plan.json"
    with open(plan_path, "w") as f:
        json.dump(plan_data, f, indent=2)
    print(f"Wrote {planner_name} plan to {plan_path}")


def final_output_step(task_id, target_output, content):
    return {
        "task_id": task_id,
        "action": "create_file",
        "path": target_output,
        "content": content,
        "requires": [],
        "produces": [
            {
                "artifact_id": "A.FINAL_OUTPUT",
                "path": target_output,
            }
        ],
    }


def is_dependency_handoff_goal(contract, target_output):
    text = " ".join(
        str(contract.get(key, ""))
        for key in ["raw_user_prompt", "intent", "cleaned_goal", "execution_prompt"]
    ).lower()
    return target_output == "dependency_report.md" or "artifact dependency" in text


def main():
    parser = argparse.ArgumentParser(description="Route goal contract to appropriate planners")
    parser.add_argument("--run-id", required=True, help="Run identifier")
    parser.add_argument("--skill-context", default=None, help="Path to skill_context.json (QRSPI skills)")
    args = parser.parse_args()
    run_dir = Path(".agentic-runs") / args.run_id
    contract = load_contract(run_dir)
    # Determine complexity – default to SIMPLE if not specified
    complexity = contract.get("complexity_level", "SIMPLE").upper()
    target_output = first_final_output(contract, "artifacts/output.txt")
    print(f"Complexity detected: {complexity}")
    # Generate plans based on complexity
    if is_dependency_handoff_goal(contract, target_output):
        planners = ["planner-minimal", "planner-robust"]
        steps = [
            {
                "task_id": "T1",
                "action": "create_file",
                "path": "artifacts/source.txt",
                "content": "source artifact produced by T1\n",
                "requires": [],
                "produces": [
                    {
                        "artifact_id": "A.SOURCE",
                        "path": "artifacts/source.txt",
                    }
                ],
            },
            {
                "task_id": "T2",
                "action": "create_file",
                "path": target_output,
                "content": "# Dependency Report\n\nConsumed exact artifact ID: A.SOURCE\n",
                "requires": ["A.SOURCE"],
                "produces": [
                    {
                        "artifact_id": "A.REPORT",
                        "path": target_output,
                    }
                ],
            },
        ]
    elif complexity == "SIMPLE":
        planners = ["planner-minimal"]
        steps = [
            final_output_step(
                "T1",
                target_output,
                "# Simple Goal\n\nGenerated by the Mercury harness.\n",
            )
        ]
    elif complexity == "MEDIUM":
        planners = ["planner-minimal", "planner-robust", "planner-skeptic"]
        steps = [
            final_output_step(
                "T1",
                target_output,
                "# Examples\n\n- Example 1\n- Example 2\n- Example 3\n",
            )
        ]
    elif complexity == "HARD":
        planners = ["planner-minimal", "planner-robust", "planner-skeptic", "planner-fast", "planner-quality"]
        steps = [
            final_output_step(
                "T1",
                target_output,
                "#!/usr/bin/env python3\n\nimport csv\nimport os\nimport sys\n\n\ndef find_csv():\n    here = os.path.dirname(__file__)\n    candidates = [\n        sys.argv[1] if len(sys.argv) > 1 else '',\n        os.path.join(here, 'data.csv'),\n        os.path.join(here, 'artifacts', 'data.csv'),\n    ]\n    for candidate in candidates:\n        if candidate and os.path.isfile(candidate):\n            return candidate\n    return None\n\n\ndef main():\n    csv_path = find_csv()\n    if not csv_path:\n        print('data.csv not found')\n        sys.exit(1)\n    with open(csv_path, newline='') as f:\n        reader = csv.reader(f)\n        rows = list(reader)\n    if not rows:\n        print('Rows: 0')\n        print('Columns: 0')\n        return\n    header = rows[0]\n    data_rows = rows[1:]\n    print(f'Rows: {len(data_rows)}')\n    print(f'Columns: {len(header)}')\n\n\nif __name__ == '__main__':\n    main()\n",
            )
        ]
    else:
        # IMPOSSIBLE or unknown – generate a step that will likely fail
        planners = ["planner-minimal"]
        steps = [
            final_output_step(
                "T1",
                target_output,
                "This is an impossible goal placeholder.",
            )
        ]
    # Write a plan for each planner
    for planner_name in planners:
        plan = {"planner": planner_name, "steps": steps}
        write_plan(run_dir, planner_name, plan)
    # In a full implementation, a selector and merger would run next.

if __name__ == "__main__":
    main()
